Repository pankod/superplate-core-plugins, pull requests merged in 2021-09, with the labels that each got.

#227 Update i18n Header
  refine/plugins/i18n/src/components/header/index.tsx
  refine/template/src/App.tsx
Labels: pr-ready, auto-merge

#226 Add layout customization prompt
  refine/_prompt.js
  refine/plugins/custom-layout/extend.js
  refine/plugins/custom-layout/public/refine-collapsed.svg
  refine/plugins/custom-layout/public/refine.svg
  refine/plugins/custom-layout/src/components/footer/index.tsx
  refine/plugins/custom-layout/src/components/header/index.tsx
  refine/plugins/custom-layout/src/components/index.ts
  refine/plugins/custom-layout/src/components/layout/index.tsx
  refine/plugins/custom-layout/src/components/offLayoutArea/index.tsx
  refine/plugins/custom-layout/src/components/sider/index.tsx
  refine/plugins/custom-layout/src/components/sider/styles.ts
  refine/plugins/custom-layout/src/components/title/index.tsx
  refine/template/src/App.tsx
Labels: review-required, auto-merge

#228 Fix conflict between i18n and custom-layout plugins
  refine/plugins/i18n/extend.js
  refine/plugins/i18n/src/components/index.ts
Labels: review-required, auto-merge

#229 Remove duplicate items from arrays in the extend.js
  nextjs/plugins/styled-components/extend.js
  refine/plugins/auth0-auth-provider/extend.js
  refine/plugins/custom-json-rest-data-provider/extend.js
  refine/plugins/google-auth-provider/extend.js
  refine/plugins/i18n/extend.js
  refine/plugins/nestjsx-crud-data-provider/extend.js
  refine/plugins/strapi-data-provider/extend.js
Labels: review-required, auto-merge

#233 add import translations
  refine/plugins/i18n/public/locales/de/common.json
  refine/plugins/i18n/public/locales/en/common.json
Labels: enhancement, review-required, pr-ready, auto-merge

#235 remove buggy trigger styles
  refine/plugins/custom-layout/src/components/sider/index.tsx
  refine/plugins/less/src/styles/antd.less
Labels: bug, review-required, auto-merge
